#!/usr/bin/env bash

export PATH="/home/pi/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
source "/home/pi/.poetry/env"

cd /opt/pyramid/triangles
pyenv local

exec poetry run python go_tri.py --bind 192.168.0.2 --fail-hard
