# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ArtNetConfigMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ArtNetConfigMessages.proto',
  package='ola.plugin.artnet',
  syntax='proto2',
  serialized_pb=_b('\n\x1a\x41rtNetConfigMessages.proto\x12\x11ola.plugin.artnet\"T\n\x0eOptionsRequest\x12\x12\n\nshort_name\x18\x01 \x01(\t\x12\x11\n\tlong_name\x18\x02 \x01(\t\x12\x0e\n\x06subnet\x18\x03 \x01(\x05\x12\x0b\n\x03net\x18\x04 \x01(\x05\"b\n\x0cOptionsReply\x12\x0e\n\x06status\x18\x01 \x02(\r\x12\x12\n\nshort_name\x18\x02 \x02(\t\x12\x11\n\tlong_name\x18\x03 \x02(\t\x12\x0e\n\x06subnet\x18\x04 \x02(\x05\x12\x0b\n\x03net\x18\x05 \x02(\x05\"#\n\x0fNodeListRequest\x12\x10\n\x08universe\x18\x01 \x02(\x05\" \n\nOutputNode\x12\x12\n\nip_address\x18\x01 \x02(\r\"<\n\rNodeListReply\x12+\n\x04node\x18\x01 \x03(\x0b\x32\x1d.ola.plugin.artnet.OutputNode\"\xf3\x01\n\x07Request\x12\x34\n\x04type\x18\x01 \x02(\x0e\x32&.ola.plugin.artnet.Request.RequestType\x12\x32\n\x07options\x18\x02 \x01(\x0b\x32!.ola.plugin.artnet.OptionsRequest\x12\x35\n\tnode_list\x18\x03 \x01(\x0b\x32\".ola.plugin.artnet.NodeListRequest\"G\n\x0bRequestType\x12\x1a\n\x16\x41RTNET_OPTIONS_REQUEST\x10\x01\x12\x1c\n\x18\x41RTNET_NODE_LIST_REQUEST\x10\x02\"\xe3\x01\n\x05Reply\x12\x30\n\x04type\x18\x01 \x02(\x0e\x32\".ola.plugin.artnet.Reply.ReplyType\x12\x30\n\x07options\x18\x02 \x01(\x0b\x32\x1f.ola.plugin.artnet.OptionsReply\x12\x33\n\tnode_list\x18\x03 \x01(\x0b\x32 .ola.plugin.artnet.NodeListReply\"A\n\tReplyType\x12\x18\n\x14\x41RTNET_OPTIONS_REPLY\x10\x01\x12\x1a\n\x16\x41RTNET_NODE_LIST_REPLY\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='ola.plugin.artnet.Request.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARTNET_OPTIONS_REQUEST', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARTNET_NODE_LIST_REQUEST', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=541,
  serialized_end=612,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_REQUESTTYPE)

_REPLY_REPLYTYPE = _descriptor.EnumDescriptor(
  name='ReplyType',
  full_name='ola.plugin.artnet.Reply.ReplyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARTNET_OPTIONS_REPLY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARTNET_NODE_LIST_REPLY', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=777,
  serialized_end=842,
)
_sym_db.RegisterEnumDescriptor(_REPLY_REPLYTYPE)


_OPTIONSREQUEST = _descriptor.Descriptor(
  name='OptionsRequest',
  full_name='ola.plugin.artnet.OptionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='short_name', full_name='ola.plugin.artnet.OptionsRequest.short_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='long_name', full_name='ola.plugin.artnet.OptionsRequest.long_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subnet', full_name='ola.plugin.artnet.OptionsRequest.subnet', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='net', full_name='ola.plugin.artnet.OptionsRequest.net', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=133,
)


_OPTIONSREPLY = _descriptor.Descriptor(
  name='OptionsReply',
  full_name='ola.plugin.artnet.OptionsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ola.plugin.artnet.OptionsReply.status', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='short_name', full_name='ola.plugin.artnet.OptionsReply.short_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='long_name', full_name='ola.plugin.artnet.OptionsReply.long_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subnet', full_name='ola.plugin.artnet.OptionsReply.subnet', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='net', full_name='ola.plugin.artnet.OptionsReply.net', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=233,
)


_NODELISTREQUEST = _descriptor.Descriptor(
  name='NodeListRequest',
  full_name='ola.plugin.artnet.NodeListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='universe', full_name='ola.plugin.artnet.NodeListRequest.universe', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=270,
)


_OUTPUTNODE = _descriptor.Descriptor(
  name='OutputNode',
  full_name='ola.plugin.artnet.OutputNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_address', full_name='ola.plugin.artnet.OutputNode.ip_address', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=304,
)


_NODELISTREPLY = _descriptor.Descriptor(
  name='NodeListReply',
  full_name='ola.plugin.artnet.NodeListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='ola.plugin.artnet.NodeListReply.node', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=366,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='ola.plugin.artnet.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ola.plugin.artnet.Request.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='options', full_name='ola.plugin.artnet.Request.options', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_list', full_name='ola.plugin.artnet.Request.node_list', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_REQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=612,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='ola.plugin.artnet.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ola.plugin.artnet.Reply.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='options', full_name='ola.plugin.artnet.Reply.options', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_list', full_name='ola.plugin.artnet.Reply.node_list', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REPLY_REPLYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=615,
  serialized_end=842,
)

_NODELISTREPLY.fields_by_name['node'].message_type = _OUTPUTNODE
_REQUEST.fields_by_name['type'].enum_type = _REQUEST_REQUESTTYPE
_REQUEST.fields_by_name['options'].message_type = _OPTIONSREQUEST
_REQUEST.fields_by_name['node_list'].message_type = _NODELISTREQUEST
_REQUEST_REQUESTTYPE.containing_type = _REQUEST
_REPLY.fields_by_name['type'].enum_type = _REPLY_REPLYTYPE
_REPLY.fields_by_name['options'].message_type = _OPTIONSREPLY
_REPLY.fields_by_name['node_list'].message_type = _NODELISTREPLY
_REPLY_REPLYTYPE.containing_type = _REPLY
DESCRIPTOR.message_types_by_name['OptionsRequest'] = _OPTIONSREQUEST
DESCRIPTOR.message_types_by_name['OptionsReply'] = _OPTIONSREPLY
DESCRIPTOR.message_types_by_name['NodeListRequest'] = _NODELISTREQUEST
DESCRIPTOR.message_types_by_name['OutputNode'] = _OUTPUTNODE
DESCRIPTOR.message_types_by_name['NodeListReply'] = _NODELISTREPLY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY

OptionsRequest = _reflection.GeneratedProtocolMessageType('OptionsRequest', (_message.Message,), dict(
  DESCRIPTOR = _OPTIONSREQUEST,
  __module__ = 'ArtNetConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.artnet.OptionsRequest)
  ))
_sym_db.RegisterMessage(OptionsRequest)

OptionsReply = _reflection.GeneratedProtocolMessageType('OptionsReply', (_message.Message,), dict(
  DESCRIPTOR = _OPTIONSREPLY,
  __module__ = 'ArtNetConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.artnet.OptionsReply)
  ))
_sym_db.RegisterMessage(OptionsReply)

NodeListRequest = _reflection.GeneratedProtocolMessageType('NodeListRequest', (_message.Message,), dict(
  DESCRIPTOR = _NODELISTREQUEST,
  __module__ = 'ArtNetConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.artnet.NodeListRequest)
  ))
_sym_db.RegisterMessage(NodeListRequest)

OutputNode = _reflection.GeneratedProtocolMessageType('OutputNode', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUTNODE,
  __module__ = 'ArtNetConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.artnet.OutputNode)
  ))
_sym_db.RegisterMessage(OutputNode)

NodeListReply = _reflection.GeneratedProtocolMessageType('NodeListReply', (_message.Message,), dict(
  DESCRIPTOR = _NODELISTREPLY,
  __module__ = 'ArtNetConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.artnet.NodeListReply)
  ))
_sym_db.RegisterMessage(NodeListReply)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'ArtNetConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.artnet.Request)
  ))
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'ArtNetConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.artnet.Reply)
  ))
_sym_db.RegisterMessage(Reply)


# @@protoc_insertion_point(module_scope)
