# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UsbProConfigMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UsbProConfigMessages.proto',
  package='ola.plugin.usbpro',
  syntax='proto2',
  serialized_pb=_b('\n\x1aUsbProConfigMessages.proto\x12\x11ola.plugin.usbpro\"m\n\x0eParameterReply\x12\x15\n\rfirmware_high\x18\x01 \x02(\r\x12\x10\n\x08\x66irmware\x18\x02 \x02(\r\x12\x12\n\nbreak_time\x18\x03 \x02(\r\x12\x10\n\x08mab_time\x18\x04 \x02(\r\x12\x0c\n\x04rate\x18\x05 \x02(\r\"W\n\x10ParameterRequest\x12\x0f\n\x07port_id\x18\x04 \x02(\r\x12\x12\n\nbreak_time\x18\x01 \x01(\r\x12\x10\n\x08mab_time\x18\x02 \x01(\r\x12\x0c\n\x04rate\x18\x03 \x01(\r\"#\n\x11SerialNumberReply\x12\x0e\n\x06serial\x18\x01 \x02(\t\"I\n\x13PortAssignmentReply\x12\x18\n\x10port_assignment1\x18\x01 \x02(\r\x12\x18\n\x10port_assignment2\x18\x02 \x02(\r\"\xe4\x01\n\x07Request\x12\x34\n\x04type\x18\x01 \x02(\x0e\x32&.ola.plugin.usbpro.Request.RequestType\x12\x37\n\nparameters\x18\x02 \x01(\x0b\x32#.ola.plugin.usbpro.ParameterRequest\"j\n\x0bRequestType\x12\x1c\n\x18USBPRO_PARAMETER_REQUEST\x10\x01\x12\x19\n\x15USBPRO_SERIAL_REQUEST\x10\x02\x12\"\n\x1eUSBPRO_PORT_ASSIGNMENT_REQUEST\x10\x03\"\xd2\x02\n\x05Reply\x12\x30\n\x04type\x18\x01 \x02(\x0e\x32\".ola.plugin.usbpro.Reply.ReplyType\x12\x35\n\nparameters\x18\x02 \x01(\x0b\x32!.ola.plugin.usbpro.ParameterReply\x12;\n\rserial_number\x18\x03 \x01(\x0b\x32$.ola.plugin.usbpro.SerialNumberReply\x12?\n\x0fport_assignment\x18\x04 \x01(\x0b\x32&.ola.plugin.usbpro.PortAssignmentReply\"b\n\tReplyType\x12\x1a\n\x16USBPRO_PARAMETER_REPLY\x10\x01\x12\x17\n\x13USBPRO_SERIAL_REPLY\x10\x02\x12 \n\x1cUSBPRO_PORT_ASSIGNMENT_REPLY\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='ola.plugin.usbpro.Request.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='USBPRO_PARAMETER_REQUEST', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USBPRO_SERIAL_REQUEST', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USBPRO_PORT_ASSIGNMENT_REQUEST', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=484,
  serialized_end=590,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_REQUESTTYPE)

_REPLY_REPLYTYPE = _descriptor.EnumDescriptor(
  name='ReplyType',
  full_name='ola.plugin.usbpro.Reply.ReplyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='USBPRO_PARAMETER_REPLY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USBPRO_SERIAL_REPLY', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USBPRO_PORT_ASSIGNMENT_REPLY', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=833,
  serialized_end=931,
)
_sym_db.RegisterEnumDescriptor(_REPLY_REPLYTYPE)


_PARAMETERREPLY = _descriptor.Descriptor(
  name='ParameterReply',
  full_name='ola.plugin.usbpro.ParameterReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firmware_high', full_name='ola.plugin.usbpro.ParameterReply.firmware_high', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='firmware', full_name='ola.plugin.usbpro.ParameterReply.firmware', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='break_time', full_name='ola.plugin.usbpro.ParameterReply.break_time', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mab_time', full_name='ola.plugin.usbpro.ParameterReply.mab_time', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate', full_name='ola.plugin.usbpro.ParameterReply.rate', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=158,
)


_PARAMETERREQUEST = _descriptor.Descriptor(
  name='ParameterRequest',
  full_name='ola.plugin.usbpro.ParameterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port_id', full_name='ola.plugin.usbpro.ParameterRequest.port_id', index=0,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='break_time', full_name='ola.plugin.usbpro.ParameterRequest.break_time', index=1,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mab_time', full_name='ola.plugin.usbpro.ParameterRequest.mab_time', index=2,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate', full_name='ola.plugin.usbpro.ParameterRequest.rate', index=3,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=247,
)


_SERIALNUMBERREPLY = _descriptor.Descriptor(
  name='SerialNumberReply',
  full_name='ola.plugin.usbpro.SerialNumberReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serial', full_name='ola.plugin.usbpro.SerialNumberReply.serial', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=284,
)


_PORTASSIGNMENTREPLY = _descriptor.Descriptor(
  name='PortAssignmentReply',
  full_name='ola.plugin.usbpro.PortAssignmentReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port_assignment1', full_name='ola.plugin.usbpro.PortAssignmentReply.port_assignment1', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port_assignment2', full_name='ola.plugin.usbpro.PortAssignmentReply.port_assignment2', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=359,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='ola.plugin.usbpro.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ola.plugin.usbpro.Request.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='ola.plugin.usbpro.Request.parameters', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_REQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=590,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='ola.plugin.usbpro.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ola.plugin.usbpro.Reply.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='ola.plugin.usbpro.Reply.parameters', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='ola.plugin.usbpro.Reply.serial_number', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port_assignment', full_name='ola.plugin.usbpro.Reply.port_assignment', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REPLY_REPLYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=931,
)

_REQUEST.fields_by_name['type'].enum_type = _REQUEST_REQUESTTYPE
_REQUEST.fields_by_name['parameters'].message_type = _PARAMETERREQUEST
_REQUEST_REQUESTTYPE.containing_type = _REQUEST
_REPLY.fields_by_name['type'].enum_type = _REPLY_REPLYTYPE
_REPLY.fields_by_name['parameters'].message_type = _PARAMETERREPLY
_REPLY.fields_by_name['serial_number'].message_type = _SERIALNUMBERREPLY
_REPLY.fields_by_name['port_assignment'].message_type = _PORTASSIGNMENTREPLY
_REPLY_REPLYTYPE.containing_type = _REPLY
DESCRIPTOR.message_types_by_name['ParameterReply'] = _PARAMETERREPLY
DESCRIPTOR.message_types_by_name['ParameterRequest'] = _PARAMETERREQUEST
DESCRIPTOR.message_types_by_name['SerialNumberReply'] = _SERIALNUMBERREPLY
DESCRIPTOR.message_types_by_name['PortAssignmentReply'] = _PORTASSIGNMENTREPLY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY

ParameterReply = _reflection.GeneratedProtocolMessageType('ParameterReply', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERREPLY,
  __module__ = 'UsbProConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.usbpro.ParameterReply)
  ))
_sym_db.RegisterMessage(ParameterReply)

ParameterRequest = _reflection.GeneratedProtocolMessageType('ParameterRequest', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERREQUEST,
  __module__ = 'UsbProConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.usbpro.ParameterRequest)
  ))
_sym_db.RegisterMessage(ParameterRequest)

SerialNumberReply = _reflection.GeneratedProtocolMessageType('SerialNumberReply', (_message.Message,), dict(
  DESCRIPTOR = _SERIALNUMBERREPLY,
  __module__ = 'UsbProConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.usbpro.SerialNumberReply)
  ))
_sym_db.RegisterMessage(SerialNumberReply)

PortAssignmentReply = _reflection.GeneratedProtocolMessageType('PortAssignmentReply', (_message.Message,), dict(
  DESCRIPTOR = _PORTASSIGNMENTREPLY,
  __module__ = 'UsbProConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.usbpro.PortAssignmentReply)
  ))
_sym_db.RegisterMessage(PortAssignmentReply)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'UsbProConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.usbpro.Request)
  ))
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'UsbProConfigMessages_pb2'
  # @@protoc_insertion_point(class_scope:ola.plugin.usbpro.Reply)
  ))
_sym_db.RegisterMessage(Reply)


# @@protoc_insertion_point(module_scope)
