# These imports include submodules under the `shows` namespace (e.g. shows.UpDown is available).
from .cycle_hsv import CycleHSV
from .left_to_right import LeftToRight
from .left_to_right_and_back import LeftToRightAndBack
from .marching_hexes import MarchingHexes
#from .one_by_one import OneByOne
from .random_cells import Random
from .showbase import ShowBase, load_shows, random_shows
#from .stargate import Stargate
from .rain import Rain
from .circling import Circling
from .strobe import Strobe
from .movingpyramids import MovingPyramids
from .marching_hexes import MarchingHexes
from .top_down import TopDown
from .tendrils import Tendrils
from .warp import Warp
#from .roar import Roar
from .sparkles import Sparkles
from .gears import Gears
#from .circling import Circling
from .index_debug import IndexDebug
from .universe_debug import UniverseDebug
from .ripples import Ripples
from .color_pulse import ColorPulse
from .strobe2 import Strobe2
from .simple_color import SimpleColor
from .up_down import UpDown
from .fuck_your_burn import FuckYourBurn
